name: test-approval2
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  builda-app:
    # environment: production
    runs-on: ubuntu-latest
    steps:
      - name: install dependency
        run: echo "install dependency"
      - name: build app
        run: echo "build app success"
  wait-for-approval:
    needs: [builda-app]
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Deploy to Appservice
        run: echo "deploy app success"
